services:
  local-mysql:
    image: mysql
    container_name: techup-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    platform: linux/arm64

  local-redis:
    image: redis
    container_name: techup-redis
    ports:
      - "6379:6379"
    platform: linux/arm64

  localstack:
    image: localstack/localstack
    container_name: techup-localstack
    ports:
      - "4566:4566"
    volumes:
      - "./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
    entrypoint: >
      /bin/sh -c "chmod +x /etc/localstack/init/ready.d/init-s3.sh && /usr/local/bin/docker-entrypoint.sh"